### ISSUE TITLE
aux current and aux voltage fields are missing in r10_hms message definition 

### ISSUE THREAD

**Issue by akshar-ra** [rangeaero-pvt-ltd/mavlink#3]
In feature branch for hms logging, aux current and aux voltage fields are missing as per the file shared by power team. The file is attached below.  The message field names must be renamed as they have generic names in the feature branch.  
https://docs.google.com/spreadsheets/d/1EmH8WEX4AgNv704mBEvXl1sz58KG65P3ZwDqU7zv6Mo/edit?usp=sharing

**Comment by Hannan121** [comment]
Its in the PMU_BAT_DATA message, I had included it there based on list from rahul

**Comment by rahul-jayaprakash-ra** [comment]
@akshar-ra  @Hannan121 , renaming the message ID fields would require changing DLB code. It will take a bit of time. It it needs to be done, then it is better to add it as task in the new timeline.

**Comment by akshar-ra** [comment]
Noted.  Will create a seperate task to tackle this issue
